# Site settings
title: The Hitchhiker's Club
email: ferro@cimat.mx
url: https://rodolfoferro.xyz/hitchhikers
baseurl: /hitchhikers
description: "The Hitchhiker's Guide to an Interconnected World. Clubes de Ciencia México, 2022."
keywords: "science, python, complex networks"
skills: "Clubes de Ciencia México. Xalapa, 2022."
meta_author: Rodolfo Ferro

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3287a8 #18bc9c #80B3FF
  primary-rgb: "50, 135, 168" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Hitchhiker's Club
  location: Location
  social: Instructors
  credits: Clubes de Ciencia

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: UV - Facultad de Ciencias Químicas
  - line: Circuito Gonzalo Aguirre Beltrán S/N, Zona Universitaria. Xalapa, VER.

# Credits content
credits: 'Join the science education revolution at <a href="https://clubesdeciencia.mx/" target="_blank">https://clubesdeciencia.mx</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
